// <auto-generated />
namespace EF_Formation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Student_Group_One_to_Many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_Group_One_to_Many));
        
        string IMigrationMetadata.Id
        {
            get { return "201807060931036_Student_Group_One_to_Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
